import React, { useState } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import loginCheckpoint from '@/api/auth/loginCheckpoint';
import { ActionCreator } from 'easy-peasy';
import { StaticContext } from 'react-router';
import { useFormikContext, withFormik } from 'formik';
import useFlash from '@/plugins/useFlash';
import { FlashStore } from '@/state/flashes';
import FlashMessageRender from '@/components/FlashMessageRender';
import AuthToast from '@/components/auth/AuthToast';
import AuthFooter from '@/components/auth/AuthFooter';

interface Values {
    code: string;
    recoveryCode: '';
}

type OwnProps = RouteComponentProps<Record<string, string | undefined>, StaticContext, { token?: string }>;

type Props = OwnProps & {
    clearAndAddHttpError: ActionCreator<FlashStore['clearAndAddHttpError']['payload']>;
};

const LoginCheckpointContainer = () => {
    const { isSubmitting, setFieldValue, handleSubmit, handleChange, handleBlur, values } = useFormikContext<Values>();
    const [isMissingDevice, setIsMissingDevice] = useState(false);

    return (
        <div className={'flex items-center justify-center min-h-screen'} style={{ backgroundColor: '#0b0f10' }}>
            <div className={'w-full max-w-md px-6'}>
                <div className={'mb-8'}>
                    <h1 className={'text-xl font-semibold text-white'}>Device Checkpoint</h1>
                    <p className={'mt-2 text-sm text-gray-400'}>
                        {isMissingDevice
                            ? 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account.'
                            : 'Enter the two-factor token generated by your device.'}
                    </p>
                </div>

                <AuthToast />

                <form onSubmit={handleSubmit}>
                    <div className={'mb-6'}>
                        <label
                            htmlFor={'code-checkpoint'}
                            className={'block text-sm font-medium text-gray-300 mb-1.5'}
                        >
                            {isMissingDevice ? 'Recovery Code' : 'Authentication Code'}
                        </label>
                        <input
                            type={'text'}
                            id={'code-checkpoint'}
                            name={isMissingDevice ? 'recoveryCode' : 'code'}
                            autoComplete={'one-time-code'}
                            autoFocus
                            disabled={isSubmitting}
                            onChange={handleChange}
                            onBlur={handleBlur}
                            value={isMissingDevice ? values.recoveryCode : values.code}
                            className={'w-full h-10 px-3 rounded-lg border border-gray-700/50 bg-[#192024] text-sm text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 disabled:opacity-50 disabled:cursor-not-allowed'}
                        />
                    </div>

                    <button
                        type={'submit'}
                        disabled={isSubmitting}
                        className={'w-full h-10 rounded-lg bg-blue-600 text-white text-sm font-medium hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-gray-900 disabled:opacity-50 disabled:cursor-not-allowed transition-colors'}
                    >
                        {isSubmitting ? 'Verifying...' : 'Continue'}
                    </button>
                </form>

                <div className={'mt-6 flex flex-col items-center space-y-3'}>
                    <button
                        type={'button'}
                        onClick={() => {
                            setFieldValue('code', '');
                            setFieldValue('recoveryCode', '');
                            setIsMissingDevice((s) => !s);
                        }}
                        className={'text-sm text-gray-400 hover:text-gray-300 no-underline bg-transparent border-none cursor-pointer'}
                    >
                        {!isMissingDevice ? "I've lost my device" : 'I have my device'}
                    </button>
                    <Link
                        to={'/auth/login'}
                        className={'text-sm font-medium text-blue-400 hover:text-blue-300 no-underline'}
                    >
                        Return to Login
                    </Link>
                </div>
            </div>

            <AuthFooter />
        </div>
    );
};

const EnhancedForm = withFormik<Props, Values>({
    handleSubmit: ({ code, recoveryCode }, { setSubmitting, props: { clearAndAddHttpError, location } }) => {
        loginCheckpoint(location.state?.token || '', code, recoveryCode)
            .then((response) => {
                if (response.complete) {
                    // @ts-expect-error this is valid
                    window.location = response.intended || '/';
                    return;
                }

                setSubmitting(false);
            })
            .catch((error) => {
                console.error(error);
                setSubmitting(false);
                clearAndAddHttpError({ error });
            });
    },

    mapPropsToValues: () => ({
        code: '',
        recoveryCode: '',
    }),
})(LoginCheckpointContainer);

export default ({ history, location, ...props }: OwnProps) => {
    const { clearAndAddHttpError } = useFlash();

    if (!location.state?.token) {
        history.replace('/auth/login');

        return null;
    }

    return (
        <EnhancedForm clearAndAddHttpError={clearAndAddHttpError} history={history} location={location} {...props} />
    );
};
