name: Build

on:
  pull_request:
    branches:
      - "realm/develop"

jobs:
  ui:
    name: UI
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn tsc & yarn lint & wait
      - run: yarn build:production
